apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 30001 #NodePort서비스 자체의 포트
      targetPort: 3306 #연결시킬 파드의 포트
      nodePort: 31000 #노드 자체의 포트
