apiVersion: v1
kind: Secret
metadata:
  name: my-spring-secret
type: Opaque
data:
  REDIS_HOST: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
  REDIS_PORT: MzE1MDA=
  MONGO_HOST: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
  MONGO_PORT: MzIwMDA=
  MONGO_URI: "bW9uZ29kYjovL2hvc3QuZG9ja2VyLmludGVybmFsOjMyMDAwL2RvY2tlcg=="
  MYSQL_URL: "amRiYzpteXNxbDovL2hvc3QuZG9ja2VyLmludGVybmFsOjMxMDAwL3lvdXJzc3VfZG9ja2VyP3NlcnZlclRpbWV6b25lPUFzaWEvU2VvdWwmc2VyaWVzVGltZXpvbmU9QXNpYS9TZW91bCYjY2hhcmFjdGVyRW5jb2Rpbmc9VUlEPTE="
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: cm9vdA==
