apiVersion: v1
kind: ConfigMap
metadata:
  name: my-spring-config
data:
  REDIS_HOST: host.docker.internal
  REDIS_PORT: "31500"
  MONGO_HOST: host.docker.internal
  MONGO_PORT: "32000"
  MONGO_URI: "mongodb://host.docker.internal:32000/docker"
  MYSQL_URL: "jdbc:mysql://host.docker.internal:31000/yourssu_docker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
