apiVersion: v1
kind: Service
metadata:
  name: my-spring
spec:
  type: NodePort
  selector:
    app: my-spring
  ports:
    - protocol: TCP
      port: 30004 #NodePort서비스 자체의 포트
      targetPort: 8080 #연결시킬 파드의 포트
      nodePort: 30000 #노드 자체의 포트
