apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 30002 #NodePort서비스 자체의 포트
      targetPort: 27017 #연결시킬 파드의 포트
      nodePort: 32000 #노드 자체의 포트
